#!/bin/sh

composer install --no-interaction --prefer-dist --optimize-autoloader --no-ansi

if [ ! -f ".env" ]; then
    cp .env.example .env
    php artisan key:generate
fi

php artisan serve --host=0.0.0.0 --port=8080
